version: "3.3"
services:
  api:
    container_name: api_liquibase
    image: ghcr.io/joojano/liquibase-jpa/liquibase-api:latest
    ports:
      - "10000:10000"
    depends_on:
      - db_liquibase
    network_mode: host
  db_liquibase:
    container_name: db_liquibase
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    network_mode: host